import type { Metadata } from "next";

import { AdminTable } from "@/components/admin/admin-table";
import { AdminExportPanel } from "@/components/admin/admin-export-panel";
import { Freshness, PageHeader, SectionCard } from "@/components/admin/admin-ui";
import { apiServer } from "@/lib/server-api";

export const metadata: Metadata = { title: "Reports" };

export default async function ReportsPage() {
  const [data, history] = await Promise.all([
    apiServer<{ catchments: Record<string, unknown>[]; usersByRole: Record<string, unknown>[]; asOf: string }>("/admin/reports"),
    apiServer<{ rows: Record<string, unknown>[] }>("/admin/reports/exports"),
  ]);
  return <><PageHeader eyebrow="Analytics" title="Platform reports" description="Generate governed operational, verification, user, property, reservation, and financial reports across multiple document and BI destinations." />
    <AdminExportPanel />
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)]"><SectionCard title="Catchment performance" description="Properties, verified inventory, demand, and verified revenue"><AdminTable rows={data?.catchments ?? []} filename="campushomes-catchment-report.csv" columns={[
      { key: "catchment", label: "Catchment" }, { key: "properties", label: "Properties" }, { key: "verifiedListings", label: "Verified listings" }, { key: "reservations", label: "Reservations" }, { key: "revenueUgx", label: "Revenue", format: "money" },
    ]} /></SectionCard><SectionCard title="Users by account type" description="Current account population"><AdminTable rows={data?.usersByRole ?? []} filename="campushomes-user-role-report.csv" columns={[{ key: "role", label: "Account type" }, { key: "count", label: "Users" }]} /></SectionCard></div>
    <SectionCard className="mt-5" title="Export history" description="Audited downloads, financial models, and BI publications"><AdminTable rows={history?.rows ?? []} filename="campushomes-report-export-history.csv" columns={[
      { key: "reportType", label: "Report" }, { key: "format", label: "Format" }, { key: "destination", label: "Destination" }, { key: "status", label: "Status", format: "status" }, { key: "createdBy", label: "Generated by" }, { key: "createdAt", label: "Created", format: "date" },
    ]} /></SectionCard>{data && <div className="mt-3"><Freshness asOf={data.asOf} /></div>}</>;
}
